FROM node:8-alpine
ARG NPM_TOKEN
RUN mkdir -p /usr/src \
  && apk update \
  && apk add zsh wget make git \
  && mkdir /root/.zsh \
  && git clone https://github.com/zsh-users/zsh-history-substring-search /root/.zsh/zsh-history-substring-search \
  && git clone https://github.com/zsh-users/zsh-autosuggestions /root/.zsh/zsh-autosuggestions \
  && git clone https://github.com/zsh-users/zsh-syntax-highlighting /root/.zsh/zsh-syntax-highlighting \
  && wget -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk \
  && apk add glibc-2.25-r0.apk
WORKDIR /usr/src
COPY src /usr/src
RUN yarn
EXPOSE 80 81 82 83
CMD ./node_modules/.bin/webpack --config ./webpack.config.dll.js --bail --hide-modules && ./node_modules/.bin/webpack --config ./webpack.config.client.js --bail --hide-modules && node .
