version: '2'
services:
  hire:
    image: nudj/hire:latest
    env_file: .env
    environment:
      - NODE_ENV=production
      - SPOOF_USER=false
    depends_on:
      - api
      - redis
    ports:
      - "80:80"
  api:
    image: nudj/api:latest
    depends_on:
      - db
    ports:
      - "81:81"
  redis:
    image: redis:alpine
    volumes:
      - sessionData:/data
  db:
    image: arangodb
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - dbdata:/var/lib/arangodb
    ports:
      - "8529:8529"
    command: arangod --server.authentication false
volumes:
  dbdata:
  sessionData:
