version: '2'
services:
  hire:
    image: nudj/hire:development
    environment:
      - NPM_TOKEN
    env_file: ../hire/.env
    volumes:
      - ../hire/.zshrc:/root/.zshrc
      - ../hire/src/app:/usr/src/app
      - ../hire/src/test:/usr/src/test
      - ../hire/src/.flowconfig:/usr/src/.flowconfig
      - ../hire/src/.npmrc:/usr/src/.npmrc
      - ../hire/src/nodemon.json:/usr/src/nodemon.json
      - ../hire/src/package.json:/usr/src/package.json
      - ../hire/src/webpack.config.js:/usr/src/webpack.config.js
      - ../hire/src/webpack.dll.js:/usr/src/webpack.dll.js
      - ../hire/src/yarn.lock:/usr/src/yarn.lock
      - ../hire/src/flow-typed:/usr/src/flow-typed
      - ../framework/src:/usr/src/@nudj/framework
      - ../library/src:/usr/src/@nudj/library
      - ../components/src:/usr/src/@nudj/components
      - ../api/src:/usr/src/@nudj/api
    stdin_open: true
    command: /bin/zsh
