FROM node:6.11.1
ARG NPM_TOKEN
RUN mkdir -p /usr/src && apt-get update && apt-get install -yq zsh make
WORKDIR /usr/src
COPY src /usr/src
RUN npm i -g torus-cli && npm i && npm prune
EXPOSE 80 81
CMD ./node_modules/.bin/standard && ./node_modules/.bin/mocha --recursive test
