module.exports = {
  '/onboarding': require('../pages/onboarding'),
  '/setup-network': require('../pages/import'),
  '/setup-network/:network/download-data': require('../pages/linkedin-guide-download'),
  '/setup-network/:network/upload': require('../pages/import-upload'),
  '/setup-network/:network': require('../pages/linkedin-guide-request'),
  '/onboarding/surveys/:surveySlug': require('../pages/survey'),
  '/onboarding/surveys/:surveySlug/sections/:sectionId': require('../pages/survey-section'),
  '/onboarding/surveys/:surveySlug/sections/:sectionId/:questionType/:questionId': require('../pages/survey-question'),
  '/onboarding/surveys/:surveySlug/complete': require('../pages/survey-complete'),
  '/': require('../pages/tasks'),
  '/jobs': require('../pages/jobs'),
  '/connections': require('../pages/connections'),
  '/connections/import': require('../pages/import'),
  '/surveys/:surveySlug': require('../pages/survey'),
  '/surveys/:surveySlug/sections/:sectionId': require('../pages/survey-section'),
  '/surveys/:surveySlug/sections/:sectionId/:questionType/:questionId': require('../pages/survey-question'),
  '/surveys/:surveySlug/complete': require('../pages/survey-complete'),
  '/conversations': require('../pages/conversations')
}
